# Generated by Django 4.1 on 2022-08-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("location", models.CharField(max_length=40)),
                ("logo", models.URLField(default="https://place-hold.it/100x60")),
                ("description", models.TextField()),
                ("emploee_count", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=20)),
                ("title", models.CharField(max_length=80)),
                ("picture", models.URLField(default="https://place-hold.it/100x60")),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("skills", models.TextField()),
                ("description", models.TextField()),
                ("salary_min", models.PositiveIntegerField()),
                ("salary_max", models.PositiveIntegerField()),
                ("published_at", models.BooleanField()),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="vacancy_app.company",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="vacancy_app.specialty",
                    ),
                ),
            ],
        ),
    ]
