# Generated by Django 4.1 on 2022-08-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="emploee_count",
            new_name="employee_count",
        ),
    ]
