# Generated by Django 4.1 on 2022-08-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy_app", "0002_rename_emploee_count_company_employee_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacancy",
            name="published_at",
            field=models.DateField(),
        ),
    ]
