# Generated by Django 4.1 on 2022-08-31 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vacancy_app", "0005_alter_application_written_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("surname", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Не ищу работу", "Chill"),
                            ("Рассматриваю предложения", "Review"),
                            ("Ищу работу", "Search"),
                        ],
                        max_length=25,
                    ),
                ),
                ("salary", models.PositiveIntegerField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("Стажер", "Intern"),
                            ("Джуниор", "Junior"),
                            ("Миддл", "Middle"),
                            ("Синьор", "Senior"),
                            ("Лид", "Lead"),
                        ],
                        max_length=7,
                    ),
                ),
                ("education", models.TextField()),
                ("experience", models.TextField()),
                ("portfolio", models.URLField()),
                (
                    "specialty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="vacancy_app.specialty",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
