# Generated by Django 4.1 on 2022-08-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancy_app", "0006_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="portfolio",
            field=models.URLField(null=True),
        ),
    ]
